CREATE TABLE IF NOT EXISTS Courses (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date` TEXT NOT NULL,
  `Category_id` INT NOT NULL,
  `Author_id` INT NOT NULL);


CREATE TABLE IF NOT EXISTS Categories (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(45) NOT NULL);


CREATE TABLE IF NOT EXISTS Authors (
   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL);


CREATE TABLE IF NOT EXISTS Users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL);


CREATE TABLE IF NOT EXISTS Course_User(
  `Course_id` INT NOT NULL,
  `User_id` INT NOT NULL);


CREATE TABLE IF NOT EXISTS Tags (
   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(45) NOT NULL);


CREATE TABLE IF NOT EXISTS Course_Tag(
   `Tag_id` INT NOT NULL,
   `Course_id` INT NOT NULL);


CREATE TABLE IF NOT EXISTS Img (
   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `Course_id` INT NOT NULL);


CREATE TABLE IF NOT EXISTS Video (
   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `Course_id` INT NOT NULL);